### ISSUE TITLE
Templates are not installed

### ISSUE THREAD

**Issue by mfornasa** [getsentry/sentry-auth-saml2#22]
The installation command `pip install https://github.com/getsentry/sentry-auth-saml2/archive/master.zip` does not copy the templates.

Trying to configure SAML2 I get:

```
Nov 24 15:00:30 : Traceback (most recent call last):
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
Nov 24 15:00:30 :     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
Nov 24 15:00:30 :     return self.dispatch(request, *args, **kwargs)
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
Nov 24 15:00:30 :     return view_func(*args, **kwargs)
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 212, in dispatch
Nov 24 15:00:30 :     return self.handle(request, *args, **kwargs)
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
Nov 24 15:00:30 :     return func(*args, **kwargs)
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/sentry/web/frontend/organization_auth_settings.py", line 203, in handle
Nov 24 15:00:30 :     return helper.current_step()
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 219, in current_step
Nov 24 15:00:30 :     helper=self,
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
Nov 24 15:00:30 :     return view_func(*args, **kwargs)
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 212, in dispatch
Nov 24 15:00:30 :     return self.handle(request, *args, **kwargs)
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/sentry_auth_saml2/generic/views.py", line 58, in handle
Nov 24 15:00:30 :     'forms': forms,
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 265, in respond
Nov 24 15:00:30 :     return render_to_response(template, default_context, self.request, status=status)
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/sentry/web/helpers.py", line 119, in render_to_response
Nov 24 15:00:30 :     response = HttpResponse(render_to_string(template, context, request))
Nov 24 15:00:30 :     response = HttpResponse(render_to_string(template, context, request))
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/sentry/web/helpers.py", line 115, in render_to_string
Nov 24 15:00:30 :     return loader.render_to_string(template, context)
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/django/template/loader.py", line 162, in render_to_string
Nov 24 15:00:30 :     t = get_template(template_name)
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
Nov 24 15:00:30 :     template, origin = find_template(template_name)
Nov 24 15:00:30 :   File "/www/sentry/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
Nov 24 15:00:30 :     raise TemplateDoesNotExist(name)
Nov 24 15:00:30 : TemplateDoesNotExist: sentry_auth_saml2/select-idp.html
```

**Comment by ranth1y** [comment]
I'm gettting the same stack trace https://gist.github.com/ranth1y/1ecf57f6ab9164de2f1516c4a4fad231 ,  No matter what commit i point to in my requirements.txt the template is not included.  see below: 

git+https://github.com/getsentry/sentry-auth-saml2.git@89a0249

**Comment by aleksihakli** [comment]
I'm getting the same error. The setup scripts probably do not include the templates.
