### ISSUE TITLE
Setup with generic saml creates KeyError

### ISSUE THREAD

**Issue by awartoft** [getsentry/sentry-auth-saml2#26]
Trying to connect a on-premises installation to jetbrains hub but i'm getting a 500 error when i submit the configuration 

```python
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
web_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
web_1        |     return self.dispatch(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
web_1        |     return view_func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 212, in dispatch
web_1        |     return self.handle(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
web_1        |     return func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/organization_auth_settings.py", line 203, in handle
web_1        |     return helper.current_step()
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 219, in current_step
web_1        |     helper=self,
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
web_1        |     return view_func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 212, in dispatch
web_1        |     return self.handle(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry_auth_saml2/generic/views.py", line 54, in handle
web_1        |     return helper.next_step()
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 227, in next_step
web_1        |     return self.current_step()
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/auth/helper.py", line 219, in current_step
web_1        |     helper=self,
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
web_1        |     return view_func(*args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 212, in dispatch
web_1        |     return self.handle(request, *args, **kwargs)
web_1        |   File "/usr/local/lib/python2.7/site-packages/sentry_auth_saml2/generic/views.py", line 64, in handle
web_1        |     print(request.session['auth'])
web_1        |   File "/usr/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 47, in __getitem__
web_1        |     return self._session[key]
web_1        | KeyError: 'auth'
web_1        | 15:19:02 [ERROR] django.request: Internal Server Error: /organizations/sentry/auth/ (status_code=500 request=<WSGIRequest: POST u'/organizations/sentry/auth/'>)
```

**Comment by aleksihakli** [comment]
I ran into the same error on Sentry 8.22.0.
